### ISSUE TITLE
支持模块 compile  引入 spring 框架依赖

### ISSUE THREAD

**Issue by lvjing2** [sofastack/sofa-serverless#329]
## 问题描述
基座引入 runtime base starter 之后，无法支持模块里 compile 引入 spring 依赖，

```text
Caused by: java.lang.IllegalArgumentException: class com.alipay.sofa.serverless.plugin.spring.ServerlessApplicationListener is not assignable to interface org.springframework.context.ApplicationListener
  at org.springframework.util.Assert.assignableCheckFailed(Assert.java:720)
  at org.springframework.util.Assert.isAssignable(Assert.java:651)
  at org.springframework.util.Assert.isAssignable(Assert.java:682)
  at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:483)
  ... 53 common frames omitted
```

具体原因可以查看 https://sofaserverless.gitee.io/docs/faq/import-full-springboot-in-module/

## 问题解决预期
在基座引入 base starter 下，模块也可以独立 compile 引入 spring 依赖

**Comment by lvjing2** [comment]
cc @TomorJM

**Comment by lvjing2** [comment]
待 @TomorJM 分享下
