### ISSUE TITLE
sofa-ark-maven-plugin:2.2.4 execute dependency:tree failed 

### ISSUE THREAD

**Issue by actorUser** [sofastack/sofa-serverless#366]
报错如下：
  我这边是一个大应用依赖比较多，maven比较复杂情况下 sofa-ark-maven-plugin 一直无法成功执行，但是去掉这个plugin构建是可以成功的；

[[1;31mERROR] Failed to execute goal com.alipay.sofa:sofa-ark-maven-plugin:2.2.4:repackage (default-cli) on project dynamic-appoint-app: [1;31mexecute dependency:tree failed -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.alipay.sofa:sofa-ark-maven-plugin:2.2.4:repackage (default-cli) on project dynamic-appoint-app: [1;31mexecute dependency:tree failed
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:233)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:173)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:161)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
at java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.maven.plugin.MojoExecutionException: execute dependency:tree failed
at com.alipay.sofa.ark.boot.mojo.RepackageMojo.getAllArtifactByMavenTree(RepackageMojo.java:407)
at com.alipay.sofa.ark.boot.mojo.RepackageMojo.repackage(RepackageMojo.java:334)
at com.alipay.sofa.ark.boot.mojo.RepackageMojo.execute(RepackageMojo.java:311)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:156)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:228)
... 11 more
[[1;31mERROR]
[[1;31mERROR]
[[1;31mERROR] For more information about the errors and possible solutions, please read the following articles:
[[1;31mERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[[1;31mERROR]
[[1;31mERROR] After correcting the problems, you can resume the build with the command
[[1;31mERROR] mvn <goals> -rf :dynamic-appoint-app

**Comment by actorUser** [comment]
为什么 sofa-ark-maven-plugin 扫描的是整个应用 ？ 我只是把某个module当做了plugin而已，扫描全部应用没必要吧
